# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kb < Formula
  desc "Terminal notes and Kanban boards, with notes as Markdown files"
  homepage "https://github.com/jeryldev/kb"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeryldev/kb/releases/download/v0.3.0/kb_darwin_amd64.tar.gz"
      sha256 "59789478b885feae32bd3ddcaa0fda10e50664cb741979fe97e21f4929eb6643"

      define_method(:install) do
        bin.install "kb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jeryldev/kb/releases/download/v0.3.0/kb_darwin_arm64.tar.gz"
      sha256 "1160309312755ea2df6a2b5e7950a4c74719e719e73ca0c88b65bcdedfe86238"

      define_method(:install) do
        bin.install "kb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeryldev/kb/releases/download/v0.3.0/kb_linux_amd64.tar.gz"
      sha256 "8c82dd9c81bf55718c197edbc228c4151106ad418da715626558333fad384738"
      define_method(:install) do
        bin.install "kb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeryldev/kb/releases/download/v0.3.0/kb_linux_arm64.tar.gz"
      sha256 "0a0f3a097a4e953a1a6f3d97e37f56ad2c693fcea90bcc448b630e47b21e230b"
      define_method(:install) do
        bin.install "kb"
      end
    end
  end
end
